In [1]:
import numpy as np
import os
import re
from solns import *
from copy import deepcopy

input_path = 'input_data/'

## day 9

In [4]:
### Day n input ###
x = process_input_day_n(8, input_path)
print(x)
soln_day_8(x)

[[1 3 3 ... 2 0 0]
 [2 0 1 ... 0 1 0]
 [3 1 2 ... 2 1 0]
 ...
 [3 3 3 ... 3 1 1]
 [2 1 3 ... 0 1 0]
 [3 1 1 ... 1 0 1]]


(1703, 496650)

## day 11

In [ ]:
### Day n input ###
x = process_input_day_n(11, input_path)
x_test = x[:60]
x_test

In [ ]:
each monkey:
    objects_held
    operation lambda
    test lambda
    throws_to tuple
    total objects inspected int

In [ ]:
class Monkey:

    kind = 'canine'         # class variable shared by all instances

    def __init__(self, name):
        self.name = name    # instance variable unique to each instance


In [ ]:
# scratch import
input_fn = f"""input_05.txt"""
filepath = os.path.join(input_path, input_fn)
x = []

with open(filepath) as fp:
    for line in fp:
        x.append(line)


In [6]:
## Solutions so far:
x = process_input_day_n(8, input_path)
#print(x)
print(soln_day_8(x))

(1703, 496650)
